core.entity_view_display.profile.profile.compact:
  expected_config:
    content:
      field_profile_image:
        weight: 7
        settings:
          image_link: ''
  update_actions:
    change:
      content:
        field_profile_image:
          weight: 0
          settings:
            image_link: owner
    add:
      content:
        field_profile_image:
          settings:
            avatar: '1'
