core.entity_form_display.profile.profile.default:
  expected_config:
    third_party_settings:
      field_group:
        group_profile_names_image:
          children:
            - field_profile_first_name
            - field_profile_last_name
            - field_profile_banner_image
            - field_profile_image
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_profile_names_image:
            children:
              - field_profile_nick_name
              - field_profile_first_name
              - field_profile_last_name
              - field_profile_banner_image
              - field_profile_image
